# @package _global_
defaults:
- dacboenv
optimizer:
  policy_class: dacboenv.policy.sb3_model.ModelPolicy
  policy_kwargs:
    model: /scratch/hpc-prf-intexml/tklenke/repos/dacboenv/training/dacbo_ppo_step
    model_class: stable_baselines3.PPO
  smac_cfg:
    smac_kwargs:
      acquisition_function:
        _target_: dacboenv.utils.confidence_bound.UCB
        update_beta: false
optimizer_id: DACBOEnv-SMAC3-beta-model-ppo-step
