# @package _global_
defaults:
  - _self_

optimizer:
  _target_: dacboenv.optimizer.DACBOEnvOptimizer
  _partial_: true
  smac_cfg:
    smac_class: smac.facade.blackbox_facade.BlackBoxFacade
    scenario:
      seed: ${seed}
      n_trials: ${task.optimization_resources.n_trials}
      deterministic: true
      n_workers: 1
      output_directory: ${outdir}/smac3_output
    smac_kwargs:
      dask_client: null
      overwrite: true
      initial_design:
        _target_: ${optimizer.smac_cfg.smac_class}.get_initial_design
        _partial_: true
        n_configs: 1_000_000
        max_ratio: 0.2
  observation_keys: null
  action_mode: "parameter"
  reward_keys: null
  rho: 0.05

optimizer_container_id: SMAC3
optimizer_id: DACBOEnv-SMAC3