# @package _global_
defaults:
- dacboenv
optimizer:
  policy_class: dacboenv.policy.policy.JumpParameterPolicy
  policy_kwargs:
    high: 6
    jump: 0.75
    low: -10
  smac_cfg:
    smac_kwargs:
      acquisition_function:
        _target_: dacboenv.utils.confidence_bound.UCB
        update_beta: false
optimizer_id: DACBOEnv-SMAC3-beta-jump-lth-075
