# @package _global_
defaults:
- dacboenv
optimizer:
  policy_class: dacboenv.env.policy.JumpParameterPolicy
  policy_kwargs:
    high: 10.0
    jump: 0.75
    low: 0.1
  smac_cfg:
    smac_kwargs:
      acquisition_function:
        _target_: dacboenv.utils.confidence_bound.UCB
optimizer_id: DACBOEnv-SMAC3-beta-jump-lth-075
