# @package _global_
defaults:
- dacboenv
optimizer:
  policy_class: dacboenv.env.policy.JumpParameterPolicy
  policy_kwargs:
    high: -10
    jump: 0.75
    low: -4.342966533881614e-06
  smac_cfg:
    smac_kwargs:
      acquisition_function:
        _target_: dacboenv.utils.confidence_bound.UCB
optimizer_id: DACBOEnv-SMAC3-beta-jump-htl-075
