# @package _global_
defaults:
- dacboenv
optimizer:
  policy_class: dacboenv.policy.jump.JumpParameterPolicy
  policy_kwargs:
    high: -10
    jump: 0.75
    low: 6
  smac_cfg:
    smac_kwargs:
      acquisition_function:
        _target_: dacboenv.utils.confidence_bound.UCB
        update_beta: false
optimizer_id: DACBOEnv-SMAC3-beta-jump-htl-075
