# @package _global_
defaults:
- dacboenv
optimizer:
  policy_class: dacboenv.env.policy.StaticParameterPolicy
  policy_kwargs:
    par_val: -4.342966533881614e-06
  smac_cfg:
    smac_kwargs:
      acquisition_function:
        _target_: dacboenv.utils.confidence_bound.UCB
optimizer_id: DACBOEnv-SMAC3-beta-static-high
