# @package _global_
defaults:
- dacboenv
optimizer:
  policy_class: dacboenv.env.policy.LinearParameterPolicy
  policy_kwargs:
    high: -4.342966533881614e-06
    high_to_low: true
    low: -10
  smac_cfg:
    smac_kwargs:
      acquisition_function:
        _target_: dacboenv.utils.confidence_bound.UCB
optimizer_id: DACBOEnv-SMAC3-beta-linear-htl
