# @package _global_
defaults:
- dacboenv
optimizer:
  policy_class: dacboenv.policy.policy.LinearParameterPolicy
  policy_kwargs:
    high: 6
    high_to_low: true
    low: -10
  smac_cfg:
    smac_kwargs:
      acquisition_function:
        _target_: dacboenv.utils.confidence_bound.UCB
        update_beta: false
optimizer_id: DACBOEnv-SMAC3-beta-linear-htl
