# @package _global_

optimizer_container_id: SMAC3
optimizer:
  _target_: dacboenv.optimizer.DACBOEnvOptimizer
  _partial_: true
  seed: ${seed}
  dacboenv:
    _target_: dacboenv.dacboenv.DACBOEnv
    task_ids:
      - ${task.name}
    observation_keys: ???
    action_space_class: ???
    action_space_kwargs: ???
    reward_keys: ???
    optimizer_cfg: ???
    seed: ${seed}
    reference_performance_fn: reference_performance/reference_performance.parquet
    inner_seeds:
      - ${seed}
    terminate_after_reference_performance_reached: False
    instance_selector:
      _target_: dacboenv.env.instance.RoundRobinInstanceSelector
      task_ids: ${optimizer.dacboenv.task_ids}
      seeds: ${optimizer.dacboenv.inner_seeds}