# @package _global_

dacboenv:
  task_ids:
    - ${task.name}
  inner_seeds:
    - ${seed}

optimizer_container_id: SMAC3
optimizer:
  _target_: dacboenv.optimizer.DACBOEnvOptimizer
  _partial_: true
  seed: ${seed}
  dacboenv: ${dacboenv}

