# @package _global_
seed: 1

task: ???
task_id: ???
benchmark_id: ???

experiment:
  n_workers: 2
  n_episodes: 10
  vecnormalize: false

optimizer_id: ???
optimizer:
  seed: ${seed}
  n_epochs: 10
  #n_steps: # Will be set during runtime in ppo.py  # TODO make variable for different dims in instance set
  #batch_size: ${divideint:${multiply:${experiment.n_workers},${optimizer.n_steps}},2}

dacboenv:
  instance_selector_class:
    _target_: dacboenv.env.instance.RoundRobinInstanceSelector
    _partial_: true
    offset: 0

baserundir: runs
outdir: ${baserundir}/${optimizer_id}/${benchmark_id}/${task_id}/${seed}
hydra:
  run:
    dir: ${outdir}  # /${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${baserundir}  # /${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${optimizer_id}/${benchmark_id}/${task_id}/${seed}  # those variables are set for individual jobs, therefore can only be in the subdir

