# @package _global_
task:
  objective_function:
    _target_: dacboenv.task.AlphaRuleNetDACBOObjectiveFunction
    env: ${dacboenv}
    weight_bounds: [-10, 10]
    cost: episode_length_scaled
    policy_kwargs:
      alpha_start: 0.5
      delta_alpha: 0.1
      k: 10
      weights: null
  input_space:
    _target_: carps.utils.task.InputSpace
    configuration_space: ${get_alpharulenet_configspace:${task.objective_function.weight_bounds}}
    fidelity_space:
      _target_: carps.utils.task.FidelitySpace
      is_multifidelity: false
      fidelity_type: null
      min_fidelity: null
      max_fidelity: null
    instance_space: null
  output_space:
    _target_: carps.utils.task.OutputSpace
    n_objectives: 1
    objectives:
      - ${task.objective_function.cost}
  metadata:
    _target_: carps.utils.task.TaskMetadata
    has_constraints: false
    domain: DAC
    objective_function_approximation: real
    has_virtual_time: false
    deterministic: true
    dimensions: ${get_nweights_alpharulenet:}
    search_space_n_categoricals: 0
    search_space_n_ordinals: 0
    search_space_n_integers: 0
    search_space_n_floats: ${get_nweights_alpharulenet:}
    search_space_has_conditionals: false
    search_space_has_forbiddens: false
    search_space_has_priors: false