# @package _global_


dacboenv:
  _target_: dacboenv.dacboenv.DACBOEnv
  task_ids:
    - ${task.name}
  observation_keys: ???
  action_space_class: ???
  action_space_kwargs: ???
  reward_keys: ???
  seed: ${seed}
  reference_performance_fn: reference_performance/reference_performance.parquet
  inner_seeds:
    - ${seed}
  terminate_after_reference_performance_reached: False
  instance_selector:
    _target_: dacboenv.env.instance.RoundRobinInstanceSelector
    task_ids: ${optimizer.dacboenv.task_ids}
    seeds: ${optimizer.dacboenv.inner_seeds}
  optimizer_cfg:
    # CARPS SMAC3 Optimizer Config
    smac_cfg:
      smac_class: smac.facade.blackbox_facade.BlackBoxFacade
      scenario:
        seed: ${seed}
        n_trials: ${task.optimization_resources.n_trials}
        deterministic: true
        n_workers: 1
        output_directory: ${outdir}/smac3_output
      smac_kwargs:
        dask_client: null
        overwrite: true
        initial_design:
          _target_: ${optimizer.dacboenv.optimizer_cfg.smac_cfg.smac_class}.get_initial_design
          _partial_: true
          n_configs: 1_000_000
          max_ratio: 0.2
        random_design:
          _target_: ${optimizer.dacboenv.optimizer_cfg.smac_cfg.smac_class}.get_random_design
          scenario: ${optimizer.dacboenv.optimizer_cfg.smac_cfg.scenario}
          probability: 0.0