# @package _global_

reference_performance_id: SMAC3-BlackBoxFacade

dacboenv:
  reference_performance_optimizer_id: SMAC3-BlackBoxFacade
  reference_performance_fn: reference_performance/reference_performance.parquet