# @package _global_

dacboenv:
  instance_selector:
    _target_: dacboenv.env.instance.RandomInstanceSelector
    task_ids: ${dacboenv.task_ids}
    seeds: ${dacboenv.inner_seeds}
    selector_seed: ${seed}