# @package _global_

dacboenv:
  task_ids:
    - ${task.name}
  inner_seeds:
    - ${seed}
  evaluation_mode: true

baserundir: runs_eval
optimizer_container_id: SMAC3
optimizer:
  _target_: dacboenv.optimizer.DACBOEnvOptimizer
  _partial_: true
  seed: ${seed}
  dacboenv: ${dacboenv}
  log_observations: true

