# @package _global_

dacboenv:
  observation_keys:
    - trials_passed
    - trials_left
    - has_categorical_hps
    - ubr
    - ubr_difference
    - knn_entropy
    - knn_difference
    - inc_improvement_scaled

