# @package _global_

observation_space_id: smart
dacboenv:
  observation_keys:
    - budget_percentage
    - has_categorical_hps
    - ubr
    - ubr_difference
    - knn_entropy
    - knn_difference
    - inc_improvement_scaled

