# @package _global_

dacboenv:
  action_space_class:
    _target_: dacboenv.env.action.AcqParameterActionSpace
    _partial_: true
  action_space_kwargs:
    bounds: [-6,3]
    adjustment_type: continuous
  
  optimizer_cfg:
    smac_cfg:
      smac_kwargs:
        acquisition_function:
          _target_: dacboenv.utils.confidence_bound.UCB
          update_beta: false