# @package _global_
defaults:
  - base
  - objfun: perceptron
  - ../env/opt: base
  - ../env/action: ucb_beta_continuous
  - ../env/obs: smart
  - ../env/reward: ep_done_scaled

dacboenv:
  terminate_after_reference_performance_reached: true
