# @package _global_
defaults:
  - base
  - objfun: alpharulenet
  - ../env: base
  - ../env/opt: base
  - ../env/action: wei_alpha_skip
  - ../env/obs: sawei
  - ../env/reward: symlogregret

dacboenv:
  terminate_after_reference_performance_reached: false

task:
  objective_function:
    weight_bounds: [-10, 10]
    cost: symlogregret