# @package _global_
defaults:
  - base
  - objfun: perceptron
  - ../env: base
  - ../env/opt: base
  - ../env/action: wei_alpha_continuous
  - ../env/obs: budgetpercentage
  - ../env/reward: ep_done_scaled

dacboenv:
  terminate_after_reference_performance_reached: true

task:
  objective_function:
    weight_bounds: [-10, 10]
    weight_in_log: false
    cost: episode_length_scaled_plus_logregret