# @package _global_

dacboenv:
  _target_: dacboenv.dacboenv.DACBOEnv
  task_ids: ???
  inner_seeds: ???
  observation_keys: ???
  action_space_class: ???
  action_space_kwargs: ???
  reward_keys: ???
  seed: ${seed}
  reference_performance_fn: reference_performance/reference_performance.parquet
  terminate_after_reference_performance_reached: False
  instance_selector:
    _target_: dacboenv.env.instance.RoundRobinInstanceSelector
    task_ids: ${dacboenv.task_ids}
    seeds: ${dacboenv.inner_seeds}