# @package _global_

dacboenv:
  _target_: dacboenv.dacboenv.DACBOEnv
  task_ids: ???
  inner_seeds: ???
  observation_keys: ???
  action_space_class: ???
  action_space_kwargs: ???
  reward_keys: ???
  seed: ${seed}
  reference_performance_fn: reference_performance/reference_performance.parquet
  reference_performance_optimizer_id: SMAC3-BlackBoxFacade
  terminate_after_reference_performance_reached: False
  instance_selector_class:
    _target_: dacboenv.env.instance.RoundRobinInstanceSelector
    _partial_: true